import Header from "../Header";
import Head from "next/head";

export default function Layout({
  children,
  isActive,
  setActive,
  ontoggleStateActive,
}) {
  return (
    <>
      <Head>
        <title>Marcel Epp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        isActive={isActive}
        setActive={setActive}
        ontoggleStateActive={ontoggleStateActive}
      />
      <main className="main">{children}</main>
    </>
  );
}
